'use client'
import type { Metadata } from "next";
import { Provider } from 'react-redux';
import "@styles/global.scss";
import { outfit } from "@assets/fonts/Outfit/Outfit";
import store from 'src/store/store';

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<Provider store={store}>
			<html lang="en">
				<body className={outfit.className}>{children}</body>
			</html>
		</Provider>
	);
}
