import type { Metadata } from "next";
import "@styles/global.scss";
import { outfit } from "@assets/fonts/Outfit/Outfit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
